Add output archive upload

diff --git a/.github/workflows/gen_ccache.yml b/.github/workflows/gen_ccache.yml
--- a/.github/workflows/gen_ccache.yml
+++ b/.github/workflows/gen_ccache.yml
@@ -225,6 +225,14 @@ jobs:
           merge-multiple: true
           skip-decompress: true
 
+      - name: 下载所有成功的 out 工件
+        uses: actions/download-artifact@v8
+        with:
+          pattern: out-*
+          path: ./out_release
+          merge-multiple: true
+          skip-decompress: true
+
       - name: 设置环境变量
         run: |
           TIME="$(TZ='Asia/Shanghai' date +'%y%m%d%H%M%S')"
@@ -239,11 +247,11 @@ jobs:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           echo "删除旧的 Release 和 Tag 以保持最新..."
-          gh release delete ccache-latest -y --cleanup-tag || true
+          #gh release delete ccache-latest -y --cleanup-tag || true
          
       - name: 创建发布
         id: create_release
-        uses: softprops/action-gh-release@v1
+        uses: softprops/action-gh-release@v3
         with:
           tag_name: "${{ env.TAG_HEAD }}-${{ env.TIME }}"
           name: "${{ env.TAG_HEAD }}-release-${{ env.TIME }}"
@@ -256,3 +264,4 @@ jobs:
           prerelease: false
           files: |
             ccache_release/*.tar.zst
+            out_release/*.tar.zst
